version: '3.3'
services:
  gitlab:
    image: gitlab/gitlab-ce:9.5.8-ce.0
    volumes:
      - ./gitlab/gitlab.rb:/etc/gitlab/gitlab.rb
    links:
      - redis-master
      - mailhog
    ports:
      - "127.0.0.1:8082:80" # Access GitLab in your browser at http://127.0.0.1:8082

  redis-master:
    build:
      context: ./redis
      dockerfile: ./dockerfile_master
    command: /entrypoint.sh
    expose:
      - "26379" # Port for Redis Sentinel
      - "6379"  # Port for Redis

  redis-slave:
    build:
      context: ./redis
      dockerfile: ./dockerfile_master
    command: /entrypoint.sh
    links:
      - redis-master
    expose:
      - "26379" # Port for Redis Sentinel
      - "6379"  # Port for Redis

  mailhog:
    image: mailhog/mailhog
    ports:
      - "127.0.0.1:8025:8025" # Access MailHog UI in your browser at http://127.0.0.1:8025
